config/routes.rb
Rails.application.routes.draw do
  
  resources :rms
  get 'sessions/new'

  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rm.rb
class Rm < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/rms_controller.rb
class RmsController < ApplicationController
  before_action :set_rm, only: [:show, :edit, :update, :destroy]

  def index
    @rms = Rm.all
  end

  def show
  end

  def new
    @rm = Rm.new
  end

  def edit
  end

  def create
    @rm = Rm.new(rm_params)

    respond_to do |format|
      if @rm.save
        format.html { redirect_to @rm, notice: 'Rm was successfully created.' }
        format.json { render :show, status: :created, location: @rm }
      else
        format.html { render :new }
        format.json { render json: @rm.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rm.update(rm_params)
        format.html { redirect_to @rm, notice: 'Rm was successfully updated.' }
        format.json { render :show, status: :ok, location: @rm }
      else
        format.html { render :edit }
        format.json { render json: @rm.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rm.destroy
    respond_to do |format|
      format.html { redirect_to rms_url, notice: 'Rm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_rm
      @rm = Rm.find(params[:id])
    end

    def rm_params
      params.require(:rm).permit(:user_id, :content, :quantity, :max)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rms_helper.rb
module RmsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManualLogin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <% if logged_in? %>
      <li><%= link_to "Users", '#' %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", '#' %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: "delete" %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Log in", login_path %></li>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/rms/_form.html.erb
<%= form_for(rm) do |f| %>
  <% if rm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rm.errors.count, "error") %> prohibited this rm from being saved:</h2>

      <ul>
      <% rm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :quality %>
    <%= f.text_field :quality %>
  </div>

  <div class="field">
    <%= f.label :max %>
    <%= f.text_field :max %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rms/edit.html.erb
<h1>Editing Rm</h1>

<%= render 'form', rm: @rm %>

<%= link_to 'Show', @rm %> |
<%= link_to 'Back', rms_path %>

app/views/rms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th>Quality</th>
      <th>Max</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rms.each do |rm| %>
      <tr>
        <td><%= rm.user_id %></td>
        <td><%= rm.content %></td>
        <td><%= rm.quantity %></td>
        <td><%= rm.max %></td>
        <td><%= link_to 'Show', rm %></td>
        <td><%= link_to 'Edit', edit_rm_path(rm) %></td>
        <td><%= link_to 'Destroy', rm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rm', new_rm_path %>

app/views/rms/new.html.erb
<h1>New Rm</h1>

<%= form_for(@rm) do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <%= f.select :content, ['Back squat', 'Front squat', 'Deadlift',
                          'Sumo Deadlift', 'Sumo Deadlift High Pull',
                          'Power Snatch', 'Power Clean',
                          'Squat Clean', 'Muscle Snatch',
                          'Clean & Jerk', 'Thruster', 'Push Jerk',
                          'Split Jerk', 'Press',
                          'Push press', 'Cluster', 'Overhead Squat']%>

  <%= f.label :max, "Max reps" %>
  <%= f.text_field :max, class: 'form-control' %>

  <%= f.label :quantity, "Weight lifted" %>
  <%= f.text_field :quantity, class: 'form-control' %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back', rms_path %>

app/views/rms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rm.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @rm.content %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @rm.quantity %>
</p>

<p>
  <strong>Max:</strong>
  <%= @rm.max %>
</p>

<%= link_to 'Edit', edit_rm_path(@rm) %> |
<%= link_to 'Back', rms_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= current_user.inspect %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>